### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by Izre** [Insane96/IguanaTweaksExpanded#1]
Problem:
Won't start

Versions:
Minecraft: 1.20.1
Forge: 47.2.0
Survival Reimagined: 0.17.1
InsaneLib: 1.12.1

Logs :  
pastebin.com/F8KLb4dj

Mods:
EnhancedAI-2.0.3-mc1.20.1
InsaneLib-1.12.1-mc1.20.1
MaxHealthFix-Forge-1.20.1-12.0.2
MobsPropertiesRandomness-4.8.0-mc1.20.1
Pehkui-3.7.11+1.20.1-forge
SereneSeasons-1.20.1-9.0.0.46
Shields+-1.7.2-mc1.20.1
SurvivalReimagined-0.17.1-mc1.20.1
tl_skin_cape_forge_1.20_1.20.1-1.32

**Comment by Insane96** [comment]
Wrong version of Shields+

Il Mar 28 Nov 2023, 16:10 Izre ***@***.***> ha scritto:

**Comment by Insane96** [comment]
No follow up. Closing
