### ISSUE TITLE
Enchantment descriptions crash if there are 8 or more enchantments on the item

### ISSUE THREAD

**Issue by The-Arcanian** [Insane96/IguanaTweaksExpanded#10]
**Versions**:
* Minecraft: 1.20.1
* Forge: 47.3.0
* IguanaTweaks Reborn: 3.21.4
* Iguana Tweaks Expanded: 1.17.3
* InsaneLib: 1.15.1

**What Happens**:  
Trying to hold shift on enchanted books created via Apotheosis's enchanting table can cause the game to crash based on some combinations of enchants.

**Logs / Crash reports**:
https://gist.github.com/The-Arcanian/eace7a7af84c31b90abf38ce65ed48ff

**Configs for ITR and ITE**:
https://gist.github.com/The-Arcanian/1853c5aac4ef5081a2f8d160d1f0e458

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes. All enabled mods in the log should be the minimal set. Apotheosis, Iguana Tweaks Expanded, and their dependencies.

**Comment by Insane96** [comment]
Is Enhanced AI mandatory?

Anyway, does it happen with ITR only? You also have ITE

**Comment by The-Arcanian** [comment]
Huh? Enhanced AI is a dependency of ITE. It won't run without it.

But no, it does not happen with only ITR, the most recent book that caused it had ITE enchants on it and does not cause a crash when ITE is disabled.

**Comment by Insane96** [comment]
Which enchantments had the book?

**Comment by The-Arcanian** [comment]
I do not believe it was always these enchantments, but the latest book to cause the crash has these ones.
![image](https://github.com/user-attachments/assets/ac666a2f-e5af-4809-9b59-b529d18af252)

It probably goes without saying which are from where, but for completeness:
Fragility, Frenzy, Ender, and Reach are from ITE. At least according to JEI.
Berserker's Fury and Life-Mending are from Apotheosis.
The other two are obviously Vanilla.

Unbreaking's modification from ITR ***is*** enabled, while Apotheosis' enchanting bypasses ITR's new 5-level limit. But, the crash only happens if I have ITE enabled. Even changing "Less unbreakable unbreaking" to false while ITE enabled does not stop it, so it is not that.

**Comment by The-Arcanian** [comment]
More crashing books.
![image](https://github.com/user-attachments/assets/54e952d8-57f1-4e98-8415-fa0344d70ce6)
![image](https://github.com/user-attachments/assets/c75c493a-2c93-499d-89ab-f8d1be86fc0b)
![image](https://github.com/user-attachments/assets/f2931224-b586-4fec-92f3-34b44c4d44fa)
![image](https://github.com/user-attachments/assets/7c4a2f16-2157-49a2-b656-5cdb1bf7c106)

Recreating the first of these books either with Apotheosis' library block or an Anvil causes the crash, even if all the enchantments are at level 1. I have not yet found a smaller combination of the enchantments that causes the crash.

**Comment by The-Arcanian** [comment]
There are no two pairs of enchantments from the second book I screenshotted that cause a crash. And looking back at the data so far I don't think it is the enchantments themselves.

Every book that is causing a crash has eight enchantments and one of the errors looks to be reporting an out-of-index render error. I think the crash is related to the "Enchantments info" feature being unable to handle eight enchantments on one item.

**Comment by Insane96** [comment]
This bug is related to IguanaTweaks Reborn, not Expanded.

**Comment by Insane96** [comment]
Fixed for next ITR update

**Comment by The-Arcanian** [comment]
Ya, I misidentified the bug's source because ITE added more enchantments making it easier to hit the 8+ overflow state. My bad.

But since we are here, might I suggest using .desc data for enchantment descriptions like every other mod seems to instead of .info data? Otherwise your `"Enchantments info"` feature is likely to often just get turned off in favor of something more widely applicable like the Enchantment Descriptions mod.

**Comment by Insane96** [comment]
I plan on removing this feature in favor of Enchantment Descriptions for 1.21
