### ISSUE TITLE
Soul Steel does not disable.

### ISSUE THREAD

**Issue by The-Arcanian** [Insane96/IguanaTweaksExpanded#11]
**Versions**:
* Minecraft:  1.20.1
* Forge: 47.3.0
* IguanaTweaks Reborn: 3.21.4
* Iguana Tweaks Expanded: 1.17.3
* InsaneLib: 1.15.1

**What Happens**:
Changing "Enable Soul Steel" to false does not disable Soul Steel

**Logs / Crash reports**:
https://gist.github.com/The-Arcanian/c469de498577515628c96a2c6eb85300

**Config**:
https://gist.github.com/The-Arcanian/635539b593d688eb94da7e62f2501fa5

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:
Yes, just Iguana Tweaks Expanded and its dependencies.

**Comment by Insane96** [comment]
Define "disable". Recipes and such require a data pack

**Comment by The-Arcanian** [comment]
I would expect that when `"Enable Soul Steel"=true` that Soul Steel and its items would exist and have recipes.
Conversely, I would expect when `"Enable Soul Steel"=false` that Soul Steel and its items would not exist, or at very have no recipes, and that the texture for Flint and Steel would be the vanilla one.

But none of that second case is true, the config for Soul Steel has no effect on it being enabled or not.

**Comment by Insane96** [comment]
I don't remember if has any effects, but

* past 1.13 items can no longer be removed
* recipes and such are data packs
* the texture change is a completely different resource pack iirc

**Comment by The-Arcanian** [comment]
* What? Don't you just need to not create them the next time Minecraft loads or something? If you load a world without a mod that was previously active the world still loads, the modded elements are just removed.
* Data packs that are only supposed to load when the config is set to `true` correct? I am saying that they are loading even when the config is set to `false`.
* `"Enable Soul Steel"` is the only thing in the whole config related to Soul Steel. The resource pack that changes the texture for Flint and Steel should be directly dependent on its state.

**Comment by Insane96** [comment]
* Since 1.13 is not advised to remove items. It's better just disabling ways of obtaining it.
* There is no data pack for soul steel, it's integrated in the mod's data so would not disable like many other things
* Will specify in the config description that disabling it will do nothing

1.21 will probably work differently, but I have no plans right now to rewrite everything

**Comment by The-Arcanian** [comment]
That's unfortunate, I like some of the ideas in this mod, but the lack of certain elements of configurability is frustrating when trying to make a pack.

**Comment by Insane96** [comment]
You can configure it, it's not as easy as setting false to a config option

**Comment by The-Arcanian** [comment]
While I don't doubt you on that, the base knowledge and effort requirements to do so appear to be higher than any other current content mod I know of. That being removing recipes, hiding items, and re-overwriting textures, at the very least. While that is all something I can figure out (I only don't know texture overwrites via KubeJS), I am still debating if it is worth the effort.

**Comment by Insane96** [comment]
I know, it's tricky, but it's also tricky making a data pack (and expecially resource pack) for everything to disable (considering that everything is usually generated from code). Right now I have no plan on adding such data pack but I have plans to make Soul Steel and other new materials standalone mods, so you can just not install them if you don't want.
