### ISSUE TITLE
Can't disable Feature. 

### ISSUE THREAD

**Issue by thedeviantknight** [Insane96/IguanaTweaksExpanded#3]
**Versions**:
* Minecraft:  1.20.1
* Forge: 47.2.21
* IguanaTweaks Reborn: 3.5.6
* InsaneLib: 1.13.2

**What Happens**:  
I can't disable the Item Module or a feature within the item module.
Example: I disable the Flint Expansion within the Item module, load a new world and Flint still spawns on the ground, and I can search and craft Flint tools. It also still persists if I disable the entire item module. 

Now this is happening with about 150 mods, but I did do a test with just Iguana Tweaks Reborn, Distant Horizons, Oculus, Embeddium, and all the mods that are required and optional (time control, mobs properties randomness, etc.) and still get the problem. 

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**Logs / Crash reports**:  
https://pastebin.com/A5dnX838

//If different from default
**Config**:  
https://pastebin.com/dyhdndmL

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes

**Comment by Insane96** [comment]
You need to use datapack to disable recipes and worldgen stuff

**Comment by Insane96** [comment]
Still, fixed that some features can be disabled and had no effect disabling them
