### ISSUE TITLE
Feature Order Cycle

### ISSUE THREAD

**Issue by SendHelpAAAA** [Insane96/IguanaTweaksExpanded#8]
Hi, there's a crash between Terralith and ITE. ITE is injecting its ores in an incorrect order, causing a Feature Order Cycle when Terralith is installed. here's the crash log with Cyanide installed to display the full cycle

[crash-2024-06-29_04.36.37-server.txt](https://github.com/user-attachments/files/16039527/crash-2024-06-29_04.36.37-server.txt)

**Comment by Insane96** [comment]
There's no way to fix this. The injection is done by Forge

**Comment by Insane96** [comment]
Uhm, might be a bug in the data pack, will release a new version soon, should fix this

**Comment by SendHelpAAAA** [comment]
> There's no way to fix this. The injection is done by Forge

Sorry! I was told that was the issue by the people helping me figure out what was causing the crash.

**Comment by Insane96** [comment]
This should be fixed
